version: '3.3'

services:
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    volumes:
      - ./nginx/flask.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    restart: always
    depends_on:
      - app

  app:
    build: .
    container_name: user_greeting_service
    expose:
      - 9090
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
    depends_on:
     - redis
    
  redis:
    image: redis:alpine3.16
    container_name: redis
    restart: always
    expose:
      - 6379
    volumes:
        - redis:/data

volumes:
  redis:
    external: false