version: '3.3'

services:
  app:
    build: user_greeting_service
    ports:
     - 9090:9090
    restart: always
    depends_on:
     - redis
    
  redis:
    image: redis:alpine3.16
    ports:
      - 6379:6379
    restart: always
    volumes:
        - redis:/data

  nginx:
    build: nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - app

volumes:
  redis:
    external: false