name: Continous Integration

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    
concurrency:
  group: continous-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9