name: Continous Integration

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    
concurrency:
  group: continous-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docker:
    name: Build Docker base images and setup environment
    runs-on: ubuntu-20.04

    steps:
      # Due to an issue with checking out a wrong commit, we make sure
      # to checkout HEAD commit for a pull request.
      # More details: https://github.com/actions/checkout/issues/299
      - name: Checkout pull request HEAD commit instead of merge commit 🕝
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout git repository 🕝
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-greeting-service:main-${{ github.sha }}

      - name: Build and push PR
        uses: docker/build-push-action@v3
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == 'true'
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-greeting-service:main-${{ github.sha }}